[versions]
kotlin = "1.7.20-Beta"
ktor = "2.1.0"
coroutines = "1.6.4"
serialization = "1.4.0-RC"
redis-om = "0.1.5"

[libraries]
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "serialization" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-reactive = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.4.0" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version = "3.1.1" }
mockk = { module = "io.mockk:mockk", version = "1.12.5" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-rsocket = { module = "io.rsocket.kotlin:rsocket-ktor-client", version = "0.15.4" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
spring-web = { module = "org.springframework:spring-web", version = "5.3.22" }
uuid = { module = "com.benasher44:uuid", version = "0.5.0" }
lettuce-core = { module = "io.lettuce:lettuce-core", version = "6.2.0.RELEASE" }

[bundles]
kotlin = ["kotlinx-serialization", "kotlinx-datetime", "kotlinx-coroutines"]
ktor = ["ktor-client-core", "ktor-client-rsocket", "ktor-client-content-negotiation", "ktor-serialization-kotlinx-json"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version = "2.7.2" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.0.13.RELEASE" }
