# spring
spring:
  application:
    name: stronghold-server
  main:
    lazy-initialization: true
    web-application-type: reactive
  rsocket:
    server:
      transport: tcp
      port: 7000
  config:
    activate:
      on-profile: rsocket-tcp
  data:
    redis:
      repositories:
        enabled: false
logging:
  level:
    root: info
    io:
      rsocket:
        FrameLogger: debug
---
db:
  url: ${DATABASE_URL:postgresql://localhost:5432/stronghold}
  user: ${DATABASE_USER:johndoe}
  password: ${DATABASE_PASSWORD:password}
spring:
  r2dbc:
    url: r2dbc:${db.url}
    username: ${db.user}
    password: ${db.password}
security:
  auth:
    strategy: ${AUTH_STRATEGY:renewing}
  jwt:
    secret-key: ${JWT_SECRET_KEY:ca7iiRP5wVMe/lJoKq/JlIfjQ5IDw0esrHdAWfJC+6c=}
redis:
  prefer-unix-domain-socket: ${REDIS_UNIX_DOMAIN_SOCKET:false}
  use-ssl: ${REDIS_USE_SSL:false}
  command-timeout: ${REDIS_COMMAND_TIMEOUT:30} # in seconds
  host: ${REDIS_HOST:172.20.0.2}
  port: ${REDIS_PORT:6379}
  username: ${REDIS_USERNAME:}
  password: ${REDIS_PASSWORD:password}
  database-index: ${REDIS_DB_INDEX:0}
