# spring
spring:
  application:
    name: stronghold-server
  main:
    lazy-initialization: true
    web-application-type: reactive
  rsocket:
    server:
      transport: tcp
      port: 7000
  config:
    activate:
      on-profile: rsocket-tcp
logging:
  level:
    root: info
    io:
      rsocket:
        FrameLogger: debug
---
db:
  url: ${DATABASE_URL:postgresql://localhost:5432/stronghold}
  user: ${DATABASE_USER:johndoe}
  password: ${DATABASE_PASSWORD:password}
spring:
  r2dbc:
    url: r2dbc:${db.url}
    username: ${db.user}
    password: ${db.password}
security:
  auth:
    strategy: ${AUTH_STRATEGY:renewing}
  jwt:
    secret-key: ${JWT_SECRET_KEY:testKey000}
redis:
  prefer-unix-domain-socket: ${PREFER_UNIX_DOMAIN_SOCKET:true}
  host: localhost
  port: 6379